# fly.toml app configuration file generated for cs375-project-white-cloud-4392 on 2024-08-12T15:06:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "csblackjack"
primary_region = "ewr"

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
